#if ! defined(EVENT_LIST_FILE_H)
#define EVENT_LIST_FILE_H

#include <stdint.h>
#include <stdbool.h>

enum SignaList
{
    SIGNAL_UNUSED_EVENT = 1024,
    SIGNAL_NETWORK_UP,
    SIGNAL_NETWORK_DOWN,
    SIGNAL_START_IPDRIVER_IF,
    SIGNAL_IPDRIVER_DOWN,
    SIGNAL_IPDRIVER_RUNNING,
    SIGNAL_IPDRIVER_CONNECTED,
    SIGNAL_IPDRIVER_DISCONNECTED,
    SIGNAL_IPDRIVER_IP_DOWN,
    SIGNAL_IPDRIVER_IP_UP,
    SIGNAL_MQTT_CONNECTED,
    SIGNAL_MQTT_DISCONNECTED,
    SIGNAL_MQTT_LOSTCONNECTION,
    SIGNAL_FW_UPGRADE_STARTED,
    SIGNAL_FW_UPGRADE_FINISHED,
};

#endif
